### ISSUE TITLE
Search box in top menu bar returns different results than search box on search page

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#153]
For instance, searching for 'over' in the menu bar returns OVER+5 and OVER+7, among others. However, searching for 'over' on the search page excludes these two results. 

Possible reason: on the search page, searching defaults to 'not in web dictionary' (at least, there is a 'inWeb=0' in the url, and in OVER+5 and OVER+7, In Web Dictionary is Yes). Please default to 'inWeb=' (if that is the explanation).

Also, do html-encode the search string in the menu bar box, so that searching for 'over+' actually yields results, instead of changing the '+' into a whitespace.

**Comment by richardbank** [comment]
In addition, glosses that have 'In Web Dictionary = Yes' are not included in a CSV export. We now set all occurences of 'In Web Dictionary' to 'No', but future exports should include all glosses regardless of their publication status. (this also resolved above issue cosmetically, so Publication Status was indeed the reason for the difference in results.)

**Comment by ErwinKomen** [comment]
Adding html-encoding in dictionary/views::search() makes it possible to include "+" and "-" signs in searches.
I leave the issue open, because I have not been able to reproduce the first part of the problem.

**Comment by ErwinKomen** [comment]
I think this issue is resolved now. Can we close it??

**Comment by ocrasborn** [comment]
OK; should the CSV export issue become a new separate issue, or has that been addressed in the meantime?

**Comment by ErwinKomen** [comment]
CSV issue has not been addressed -- sorry, I overlooked that. Am looking at it now.

**Comment by ErwinKomen** [comment]
Okay, found it. It should work once Wessel applies the GitHub commit.
Implementation details: 
- Look at signbank/dictionary/adminviews.py, GlossListView
- Change checking for get['inWeb'] value 'unspecified' to value '0', because the [inWeb] has choices according to NULLBOOLEANCHOICES (and not YESNOCHOICES).

**Comment by ocrasborn** [comment]
@ErwinKomen , the solution above is just for the CSV issue, right? Just checking,as I still get different search results for glosses while using the two search fields (I tried 'wes': 6 hits when using the menu bar field, 4 hits when using the field at the top of the search form.

**Comment by ErwinKomen** [comment]
The solution above was meant to be for the resolution of the search-result-mismatch-issue.
But unfortunately my github 'push' of the resolution hadn't made it.
I've now resolved and pushed it again, so it should be picked up later this week, when Wessel does something on signbank.
